name: Send Problems Email to All Subscribers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * 1,3"

jobs:
  trigger-problems-email:
    runs-on: ubuntu-latest
    env:
      API_ENDPOINT: https://vaguinhas.com.br/api/emails/send-problems-email-to-all
      API_TOKEN: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Send problems email to all subscribers
        run: |
          curl -X GET "$API_ENDPOINT" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.JWT_SECRET }}"
